# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Joseph Ekeng
description: "Hi I'm Joseph, and I'm a Business Analyst.  My portfolio focuses on interesting projects I've recently undertaken, with a strong emphasis on business impact. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Business Analyst <span style="color:#f58506"> Portfolio </span>
location: "Toronto, CAN"
resume_url: docs/Joseph_Ekeng_February.pdf
avatar_image: img/linkedinphoto.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/joseph-ekeng-477171121/" # Add your linkedln handle
github: "https://jekeng.github.io/"  # Add your github handle

paginate: 10
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

